name: CI Build and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Trigger is ${{ github.event_name }}, running on branch ${{ github.ref }}"
        echo "This is a step message."
