name: CI Build and Test Workflow

on:
  push:
    branches:
      - main
permissions:
  actions: write
  contents: write
  checks : write

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
            files: |
              test-results/**/*.xml
              test-results/**/*.trx
              test-results/**/*.json 
        
    
