name: CI Build and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2 
        if: always()
        with:
          files: target/surefire-reports/test.xml

    
